# Generated by Django 4.1.7 on 2023-04-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_booker",
                to="users.customuser",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="day_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.availabletime",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="reserver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_reserver",
                to="users.customuser",
            ),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="day_and_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appointment.daytime"
            ),
        ),
        migrations.AddField(
            model_name="availabletime",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customuser"
            ),
        ),
    ]
