# Generated by Django 4.1.7 on 2023-04-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fees",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customuser"
            ),
        ),
    ]
