# Generated by Django 4.1.7 on 2023-04-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fees",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fees.payment",
            ),
        ),
    ]
